var searchData=
[
  ['tagged_20pdf_20to_20json_2c_20xml_20and_20html_20sample',['Tagged Pdf To JSON, XML and HTML Sample',['../_convert_tagged_pdf_cpp.html',1,'CPP_Samples']]],
  ['template_20functions',['Template Functions',['../group___pdf_doc_template___functions.html',1,'']]],
  ['tagannotation',['TagAnnotation',['../classnet_1_1pdfix_1_1samples_1_1_tag_annotation.html',1,'net.pdfix.samples.TagAnnotation'],['../namespace_tag_annotation.html',1,'TagAnnotation']]],
  ['tag_20annotation_20added_20on_20a_20page',['Tag annotation added on a page',['../_tag_annotation_cpp.html',1,'CPP_Samples']]],
  ['tag_20annotation_20added_20on_20a_20page',['Tag annotation added on a page',['../_tag_annotation_cs.html',1,'CS_Samples']]],
  ['tag_20annotation_20added_20on_20a_20page',['Tag annotation added on a page',['../_tag_annotation_java.html',1,'JAVA_Samples']]],
  ['tagasartifact',['TagAsArtifact',['../classnet_1_1pdfix_1_1samples_1_1_tag_as_artifact.html',1,'net.pdfix.samples.TagAsArtifact'],['../namespace_tag_as_artifact.html',1,'TagAsArtifact']]],
  ['tagheadings',['TagHeadings',['../namespace_tag_headings.html',1,'']]],
  ['tag_20paragraph_20as_20heading',['Tag paragraph as Heading',['../_tag_headings_cpp.html',1,'CPP_Samples']]],
  ['tagseditstructtree',['TagsEditStructTree',['../classnet_1_1pdfix_1_1samples_1_1_tags_edit_struct_tree.html',1,'net::pdfix::samples']]],
  ['tagsreadingorder',['TagsReadingOrder',['../classnet_1_1pdfix_1_1samples_1_1_tags_reading_order.html',1,'net.pdfix.samples.TagsReadingOrder'],['../namespace_tags_reading_order.html',1,'TagsReadingOrder']]],
  ['tagsreadstructuretree',['TagsReadStructureTree',['../classnet_1_1pdfix_1_1samples_1_1_tags_read_structure_tree.html',1,'net::pdfix::samples']]],
  ['tagtableasfigure',['TagTableAsFigure',['../classnet_1_1pdfix_1_1samples_1_1_tag_table_as_figure.html',1,'net.pdfix.samples.TagTableAsFigure'],['../namespace_tag_table_as_figure.html',1,'TagTableAsFigure']]],
  ['tag_20elements_20as_20figure',['Tag elements as Figure',['../_tag_table_as_figure_cpp.html',1,'CPP_Samples']]],
  ['tag_20elements_20as_20figure',['Tag elements as Figure',['../_tag_table_as_figure_cs.html',1,'CS_Samples']]],
  ['tag_20elements_20as_20figure',['Tag elements as Figure',['../_tag_table_as_figure_java.html',1,'JAVA_Samples']]],
  ['tesseractdoc',['TesseractDoc',['../struct_tesseract_doc.html',1,'']]],
  ['text_5falign',['text_align',['../struct___pdf_annot_appearance.html#a24043783c22fa3028e38e3f2c7bcf373',1,'_PdfAnnotAppearance']]],
  ['thread_20safe_20use_20sample',['Thread safe use Sample',['../_thread_safe_java.html',1,'']]],
  ['threadsafepdfix',['ThreadSafePdfix',['../classnet_1_1pdfix_1_1samples_1_1_thread_safe_pdfix.html',1,'net::pdfix::samples']]],
  ['thread_20safe_20use_20sample',['Thread safe use Sample',['../_thread_safe_pdfix_cs.html',1,'CS_Samples']]],
  ['tl',['tl',['../struct___pdf_quad.html#a219d66f02225f4f57180e1aa941a769c',1,'_PdfQuad::tl()'],['../struct___pdf_dev_quad.html#a96597c56640d246795795be7cdd5d4c0',1,'_PdfDevQuad::tl()']]],
  ['top',['top',['../struct___pdf_rect.html#ae87ec15e24bab538776e6f98ec0efda8',1,'_PdfRect::top()'],['../struct___pdf_dev_rect.html#a5d4007e19e4ac34a699a2cd9c248f457',1,'_PdfDevRect::top()']]],
  ['tr',['tr',['../struct___pdf_quad.html#aabd5ba4f5a2b3ba1fab12e552a179d8a',1,'_PdfQuad::tr()'],['../struct___pdf_dev_quad.html#af294c4d482651868ca33736052017e0b',1,'_PdfDevQuad::tr()']]],
  ['type',['type',['../struct___pdf_font_state.html#a03ca7e268770d41c851d744553cb17b2',1,'_PdfFontState::type()'],['../struct___pdf_media_query_params.html#a8d61ef3d060b1e810e2061d165e40b9f',1,'_PdfMediaQueryParams::type()'],['../struct___pdf_html_params.html#a77495be14cdcf238204e93fad7c29634',1,'_PdfHtmlParams::type()']]]
];
