var _c_p_p__samples =
[
    [ "Add Comment Sample", "_add_comment_cpp.html", null ],
    [ "Add Tags Sample", "_add_tags_cpp.html", null ],
    [ "Add Watermark Sample", "_add_watermark_cpp.html", null ],
    [ "Certificate Store Digital Signature Sample", "_cert_digital_signature_cpp.html", null ],
    [ "Pdf To Html Sample", "_convert_to_html_cpp.html", null ],
    [ "PFX Digital Signature Sample", "_digital_signature_cpp.html", null ],
    [ "Get/Set Document Metadata Sample", "_document_metadata_cpp.html", null ],
    [ "EmbedFonts Sample", "_embed_fonts_cpp.html", null ],
    [ "Export Form Field Values Sample", "_export_form_field_values_cpp.html", null ],
    [ "Pdf To Text Sample", "_extract_highlighted_text_cpp.html", null ],
    [ "Pdf To Image Sample", "_extract_images_cpp.html", null ],
    [ "Pdf To Table Sample", "_extract_tables_cpp.html", null ],
    [ "Pdf To Text Sample", "_extract_text_cpp.html", null ],
    [ "Flatten Annots Sample", "_flatten_annots_cpp.html", null ],
    [ "Get Bookmarks Sample", "_get_bookmarks_cpp.html", null ],
    [ "Get Whitespace Sample", "_get_whitespace_cpp.html", null ],
    [ "Initialization Sample", "_initialization_cpp.html", null ],
    [ "Make PDF Accessible Sample", "_make_accessible_cpp.html", null ],
    [ "Ocr With Tesseract Sample", "_ocr_with_tesseract_cpp.html", null ],
    [ "Print Page Sample", "_print_page_cpp.html", null ],
    [ "Regex Search Sample", "_regex_search_cpp.html", null ],
    [ "Set Regex Pattern Sample", "_regex_set_pattern_cpp.html", null ],
    [ "Register Event Sample", "_register_event_cpp.html", null ],
    [ "Remove Comments Sample", "_remove_comments_cpp.html", null ],
    [ "Render Page Sample", "_render_page_cpp.html", null ],
    [ "Set Field Flags Sample", "_set_field_flags_cpp.html", null ],
    [ "Set Form Field Value Sample", "_set_form_field_value_cpp.html", null ]
];